/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassImbalanceRouteImport } from './routes/class-imbalance'
import { Route as ClassMetricsRouteImport } from './routes/class-metrics'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ConfigureExperimentRouteImport } from './routes/configure-experiment'
import { Route as ConfusionMatrixRouteImport } from './routes/confusion-matrix'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataDistributionRouteImport } from './routes/data-distribution'
import { Route as DpVsNonDpRouteImport } from './routes/dp-vs-non-dp'
import { Route as ExperimentHistoryRouteImport } from './routes/experiment-history'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as FedavgVsFedproxRouteImport } from './routes/fedavg-vs-fedprox'
import { Route as FederatedSetupRouteImport } from './routes/federated-setup'
import { Route as IidVsNonIidRouteImport } from './routes/iid-vs-non-iid'
import { Route as ModelImprovementRouteImport } from './routes/model-improvement'
import { Route as ModelPerformanceRouteImport } from './routes/model-performance'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as HospitalIndexRouteImport } from './routes/hospital/index'
import { Route as HospitalDatasetRouteImport } from './routes/hospital/dataset'
import { Route as HospitalGlobalModelRouteImport } from './routes/hospital/global-model'
import { Route as HospitalTrainingRouteImport } from './routes/hospital/training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassImbalanceRoute = ClassImbalanceRouteImport.update({
  id: '/class-imbalance',
  path: '/class-imbalance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassMetricsRoute = ClassMetricsRouteImport.update({
  id: '/class-metrics',
  path: '/class-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureExperimentRoute = ConfigureExperimentRouteImport.update({
  id: '/configure-experiment',
  path: '/configure-experiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfusionMatrixRoute = ConfusionMatrixRouteImport.update({
  id: '/confusion-matrix',
  path: '/confusion-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDistributionRoute = DataDistributionRouteImport.update({
  id: '/data-distribution',
  path: '/data-distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DpVsNonDpRoute = DpVsNonDpRouteImport.update({
  id: '/dp-vs-non-dp',
  path: '/dp-vs-non-dp',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentHistoryRoute = ExperimentHistoryRouteImport.update({
  id: '/experiment-history',
  path: '/experiment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const FedavgVsFedproxRoute = FedavgVsFedproxRouteImport.update({
  id: '/fedavg-vs-fedprox',
  path: '/fedavg-vs-fedprox',
  getParentRoute: () => rootRouteImport,
} as any)
const FederatedSetupRoute = FederatedSetupRouteImport.update({
  id: '/federated-setup',
  path: '/federated-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IidVsNonIidRoute = IidVsNonIidRouteImport.update({
  id: '/iid-vs-non-iid',
  path: '/iid-vs-non-iid',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelImprovementRoute = ModelImprovementRouteImport.update({
  id: '/model-improvement',
  path: '/model-improvement',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPerformanceRoute = ModelPerformanceRouteImport.update({
  id: '/model-performance',
  path: '/model-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/hospital/',
  path: '/hospital/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDatasetRoute = HospitalDatasetRouteImport.update({
  id: '/hospital/dataset',
  path: '/hospital/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalGlobalModelRoute = HospitalGlobalModelRouteImport.update({
  id: '/hospital/global-model',
  path: '/hospital/global-model',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalTrainingRoute = HospitalTrainingRouteImport.update({
  id: '/hospital/training',
  path: '/hospital/training',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/class-imbalance': typeof ClassImbalanceRoute
  '/class-metrics': typeof ClassMetricsRoute
  '/clients': typeof ClientsRoute
  '/configure-experiment': typeof ConfigureExperimentRoute
  '/confusion-matrix': typeof ConfusionMatrixRoute
  '/dashboard': typeof DashboardRoute
  '/data-distribution': typeof DataDistributionRoute
  '/dp-vs-non-dp': typeof DpVsNonDpRoute
  '/experiment-history': typeof ExperimentHistoryRoute
  '/experiments': typeof ExperimentsRoute
  '/fedavg-vs-fedprox': typeof FedavgVsFedproxRoute
  '/federated-setup': typeof FederatedSetupRoute
  '/iid-vs-non-iid': typeof IidVsNonIidRoute
  '/model-improvement': typeof ModelImprovementRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/prediction': typeof PredictionRoute
  '/hospital/dataset': typeof HospitalDatasetRoute
  '/hospital/global-model': typeof HospitalGlobalModelRoute
  '/hospital/training': typeof HospitalTrainingRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/class-imbalance': typeof ClassImbalanceRoute
  '/class-metrics': typeof ClassMetricsRoute
  '/clients': typeof ClientsRoute
  '/configure-experiment': typeof ConfigureExperimentRoute
  '/confusion-matrix': typeof ConfusionMatrixRoute
  '/dashboard': typeof DashboardRoute
  '/data-distribution': typeof DataDistributionRoute
  '/dp-vs-non-dp': typeof DpVsNonDpRoute
  '/experiment-history': typeof ExperimentHistoryRoute
  '/experiments': typeof ExperimentsRoute
  '/fedavg-vs-fedprox': typeof FedavgVsFedproxRoute
  '/federated-setup': typeof FederatedSetupRoute
  '/iid-vs-non-iid': typeof IidVsNonIidRoute
  '/model-improvement': typeof ModelImprovementRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/prediction': typeof PredictionRoute
  '/hospital/dataset': typeof HospitalDatasetRoute
  '/hospital/global-model': typeof HospitalGlobalModelRoute
  '/hospital/training': typeof HospitalTrainingRoute
  '/hospital': typeof HospitalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/class-imbalance': typeof ClassImbalanceRoute
  '/class-metrics': typeof ClassMetricsRoute
  '/clients': typeof ClientsRoute
  '/configure-experiment': typeof ConfigureExperimentRoute
  '/confusion-matrix': typeof ConfusionMatrixRoute
  '/dashboard': typeof DashboardRoute
  '/data-distribution': typeof DataDistributionRoute
  '/dp-vs-non-dp': typeof DpVsNonDpRoute
  '/experiment-history': typeof ExperimentHistoryRoute
  '/experiments': typeof ExperimentsRoute
  '/fedavg-vs-fedprox': typeof FedavgVsFedproxRoute
  '/federated-setup': typeof FederatedSetupRoute
  '/iid-vs-non-iid': typeof IidVsNonIidRoute
  '/model-improvement': typeof ModelImprovementRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/prediction': typeof PredictionRoute
  '/hospital/dataset': typeof HospitalDatasetRoute
  '/hospital/global-model': typeof HospitalGlobalModelRoute
  '/hospital/training': typeof HospitalTrainingRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/class-imbalance'
    | '/class-metrics'
    | '/clients'
    | '/configure-experiment'
    | '/confusion-matrix'
    | '/dashboard'
    | '/data-distribution'
    | '/dp-vs-non-dp'
    | '/experiment-history'
    | '/experiments'
    | '/fedavg-vs-fedprox'
    | '/federated-setup'
    | '/iid-vs-non-iid'
    | '/model-improvement'
    | '/model-performance'
    | '/prediction'
    | '/hospital/dataset'
    | '/hospital/global-model'
    | '/hospital/training'
    | '/hospital/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/class-imbalance'
    | '/class-metrics'
    | '/clients'
    | '/configure-experiment'
    | '/confusion-matrix'
    | '/dashboard'
    | '/data-distribution'
    | '/dp-vs-non-dp'
    | '/experiment-history'
    | '/experiments'
    | '/fedavg-vs-fedprox'
    | '/federated-setup'
    | '/iid-vs-non-iid'
    | '/model-improvement'
    | '/model-performance'
    | '/prediction'
    | '/hospital/dataset'
    | '/hospital/global-model'
    | '/hospital/training'
    | '/hospital'
  id:
    | '__root__'
    | '/'
    | '/class-imbalance'
    | '/class-metrics'
    | '/clients'
    | '/configure-experiment'
    | '/confusion-matrix'
    | '/dashboard'
    | '/data-distribution'
    | '/dp-vs-non-dp'
    | '/experiment-history'
    | '/experiments'
    | '/fedavg-vs-fedprox'
    | '/federated-setup'
    | '/iid-vs-non-iid'
    | '/model-improvement'
    | '/model-performance'
    | '/prediction'
    | '/hospital/dataset'
    | '/hospital/global-model'
    | '/hospital/training'
    | '/hospital/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassImbalanceRoute: typeof ClassImbalanceRoute
  ClassMetricsRoute: typeof ClassMetricsRoute
  ClientsRoute: typeof ClientsRoute
  ConfigureExperimentRoute: typeof ConfigureExperimentRoute
  ConfusionMatrixRoute: typeof ConfusionMatrixRoute
  DashboardRoute: typeof DashboardRoute
  DataDistributionRoute: typeof DataDistributionRoute
  DpVsNonDpRoute: typeof DpVsNonDpRoute
  ExperimentHistoryRoute: typeof ExperimentHistoryRoute
  ExperimentsRoute: typeof ExperimentsRoute
  FedavgVsFedproxRoute: typeof FedavgVsFedproxRoute
  FederatedSetupRoute: typeof FederatedSetupRoute
  IidVsNonIidRoute: typeof IidVsNonIidRoute
  ModelImprovementRoute: typeof ModelImprovementRoute
  ModelPerformanceRoute: typeof ModelPerformanceRoute
  PredictionRoute: typeof PredictionRoute
  HospitalDatasetRoute: typeof HospitalDatasetRoute
  HospitalGlobalModelRoute: typeof HospitalGlobalModelRoute
  HospitalTrainingRoute: typeof HospitalTrainingRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-imbalance': {
      id: '/class-imbalance'
      path: '/class-imbalance'
      fullPath: '/class-imbalance'
      preLoaderRoute: typeof ClassImbalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-metrics': {
      id: '/class-metrics'
      path: '/class-metrics'
      fullPath: '/class-metrics'
      preLoaderRoute: typeof ClassMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure-experiment': {
      id: '/configure-experiment'
      path: '/configure-experiment'
      fullPath: '/configure-experiment'
      preLoaderRoute: typeof ConfigureExperimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confusion-matrix': {
      id: '/confusion-matrix'
      path: '/confusion-matrix'
      fullPath: '/confusion-matrix'
      preLoaderRoute: typeof ConfusionMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-distribution': {
      id: '/data-distribution'
      path: '/data-distribution'
      fullPath: '/data-distribution'
      preLoaderRoute: typeof DataDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dp-vs-non-dp': {
      id: '/dp-vs-non-dp'
      path: '/dp-vs-non-dp'
      fullPath: '/dp-vs-non-dp'
      preLoaderRoute: typeof DpVsNonDpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment-history': {
      id: '/experiment-history'
      path: '/experiment-history'
      fullPath: '/experiment-history'
      preLoaderRoute: typeof ExperimentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fedavg-vs-fedprox': {
      id: '/fedavg-vs-fedprox'
      path: '/fedavg-vs-fedprox'
      fullPath: '/fedavg-vs-fedprox'
      preLoaderRoute: typeof FedavgVsFedproxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federated-setup': {
      id: '/federated-setup'
      path: '/federated-setup'
      fullPath: '/federated-setup'
      preLoaderRoute: typeof FederatedSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iid-vs-non-iid': {
      id: '/iid-vs-non-iid'
      path: '/iid-vs-non-iid'
      fullPath: '/iid-vs-non-iid'
      preLoaderRoute: typeof IidVsNonIidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-improvement': {
      id: '/model-improvement'
      path: '/model-improvement'
      fullPath: '/model-improvement'
      preLoaderRoute: typeof ModelImprovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-performance': {
      id: '/model-performance'
      path: '/model-performance'
      fullPath: '/model-performance'
      preLoaderRoute: typeof ModelPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/hospital'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/dataset': {
      id: '/hospital/dataset'
      path: '/hospital/dataset'
      fullPath: '/hospital/dataset'
      preLoaderRoute: typeof HospitalDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/global-model': {
      id: '/hospital/global-model'
      path: '/hospital/global-model'
      fullPath: '/hospital/global-model'
      preLoaderRoute: typeof HospitalGlobalModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/training': {
      id: '/hospital/training'
      path: '/hospital/training'
      fullPath: '/hospital/training'
      preLoaderRoute: typeof HospitalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassImbalanceRoute: ClassImbalanceRoute,
  ClassMetricsRoute: ClassMetricsRoute,
  ClientsRoute: ClientsRoute,
  ConfigureExperimentRoute: ConfigureExperimentRoute,
  ConfusionMatrixRoute: ConfusionMatrixRoute,
  DashboardRoute: DashboardRoute,
  DataDistributionRoute: DataDistributionRoute,
  DpVsNonDpRoute: DpVsNonDpRoute,
  ExperimentHistoryRoute: ExperimentHistoryRoute,
  ExperimentsRoute: ExperimentsRoute,
  FedavgVsFedproxRoute: FedavgVsFedproxRoute,
  FederatedSetupRoute: FederatedSetupRoute,
  IidVsNonIidRoute: IidVsNonIidRoute,
  ModelImprovementRoute: ModelImprovementRoute,
  ModelPerformanceRoute: ModelPerformanceRoute,
  PredictionRoute: PredictionRoute,
  HospitalDatasetRoute: HospitalDatasetRoute,
  HospitalGlobalModelRoute: HospitalGlobalModelRoute,
  HospitalTrainingRoute: HospitalTrainingRoute,
  HospitalIndexRoute: HospitalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
